package com.github.dungphan.unityindex.util

import com.github.dungphan.unityindex.tools.models.GraphSnapshot
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

/**
 * Day 6 Task 11: cross-implementation byte-equivalence gate.
 *
 * Loads the fixture JSON generated by `graph/core/scripts/dump-fixture.ts`
 * (committed at `src/test/resources/graph/traversal-fixture.json`) and runs
 * each query through the Kotlin `GraphTraversal`. Asserts node ID lists,
 * edge (source, target, kind) tuples, and impact classifications match the
 * TS-expected outputs exactly.
 *
 * Lockstep rule (per `docs/graph-day6-tasks.md`): if the TS-side fixture
 * changes, re-run the dump script in the same commit so this test sees the
 * new expected values.
 */
class GraphTraversalTest {

    private val json = Json {
        ignoreUnknownKeys = true
        encodeDefaults = true
    }

    @Test
    fun `neighbors queries match TS-expected outputs`() {
        val fixture = loadFixture()
        val snapshot = json.decodeFromJsonElement(GraphSnapshot.serializer(), fixture["snapshot"]!!)
        val adj = GraphTraversal.buildAdjacency(snapshot)

        val cases = fixture["queries"]!!.jsonObject["neighbors"]!!.jsonArray
        for (case in cases) {
            val obj = case.jsonObject
            val name = obj["name"]!!.jsonPrimitive.content
            val req = obj["request"]!!.jsonObject
            val expected = obj["result"]!!.jsonObject

            val seeds = req["seeds"]!!.jsonArray.map { it.jsonPrimitive.content }
            val direction = when (req["direction"]!!.jsonPrimitive.content) {
                "in" -> com.github.dungphan.unityindex.tools.models.TraversalDirection.IN
                "out" -> com.github.dungphan.unityindex.tools.models.TraversalDirection.OUT
                else -> com.github.dungphan.unityindex.tools.models.TraversalDirection.BOTH
            }
            val r = GraphTraversal.neighbors(
                adj,
                seeds,
                GraphTraversal.NeighborsOptions(
                    hops = req["hops"]!!.jsonPrimitive.int,
                    direction = direction,
                    maxNodes = req["maxNodes"]!!.jsonPrimitive.int,
                ),
            )
            val actualNodeIds = r.nodes.map { it.id }.sorted()
            val expectedNodeIds = expected["nodeIds"]!!.jsonArray.map { it.jsonPrimitive.content }
            assertEquals(expectedNodeIds, actualNodeIds, "neighbors[$name] nodeIds")

            val actualEdges = r.edges
                .map { triple(it.source, it.target, it.kind.name.lowercase().replace('_', '_')) }
                .sortedBy { it.first + it.second + it.third }
            val expectedEdges = expected["edges"]!!.jsonArray.map {
                val e = it.jsonObject
                triple(
                    e["source"]!!.jsonPrimitive.content,
                    e["target"]!!.jsonPrimitive.content,
                    e["kind"]!!.jsonPrimitive.content,
                )
            }.sortedBy { it.first + it.second + it.third }
            assertEquals(
                expectedEdges.map { it.first to it.second },
                actualEdges.map { it.first to it.second },
                "neighbors[$name] edge (source,target) tuples",
            )
            assertEquals(
                expected["truncated"]!!.jsonPrimitive.boolean,
                r.truncated,
                "neighbors[$name] truncated",
            )
        }
    }

    @Test
    fun `impact queries match TS-expected classifications and ordering`() {
        val fixture = loadFixture()
        val snapshot = json.decodeFromJsonElement(GraphSnapshot.serializer(), fixture["snapshot"]!!)
        val adj = GraphTraversal.buildAdjacency(snapshot)

        val cases = fixture["queries"]!!.jsonObject["impact"]!!.jsonArray
        for (case in cases) {
            val obj = case.jsonObject
            val name = obj["name"]!!.jsonPrimitive.content
            val seeds = obj["request"]!!.jsonObject["seeds"]!!.jsonArray.map { it.jsonPrimitive.content }
            val expected = obj["result"]!!.jsonObject

            val r = GraphTraversal.impact(
                adj,
                seeds,
                GraphTraversal.ImpactOptions(classify = true),
            )

            val expectedImpacted = expected["impacted"]!!.jsonArray.map { it.jsonObject }
            assertEquals(expectedImpacted.size, r.impacted.size, "impact[$name] count")
            for ((i, exp) in expectedImpacted.withIndex()) {
                val actual = r.impacted[i]
                assertEquals(exp["id"]!!.jsonPrimitive.content, actual.id, "impact[$name][$i] id")
                assertEquals(exp["distance"]!!.jsonPrimitive.int, actual.distance, "impact[$name][$i] distance")
                val expectedCls = (exp["classification"] as? JsonPrimitive)?.contentOrNull
                val actualCls = actual.classification?.let {
                    when (it) {
                        com.github.dungphan.unityindex.tools.models.ImpactClassification.DIRECT -> "direct"
                        com.github.dungphan.unityindex.tools.models.ImpactClassification.TRANSITIVE -> "transitive"
                        com.github.dungphan.unityindex.tools.models.ImpactClassification.WEAK -> "weak"
                    }
                }
                assertEquals(expectedCls, actualCls, "impact[$name][$i] classification")
            }
        }
    }

    @Test
    fun `context queries return matching node + endpoint counts`() {
        val fixture = loadFixture()
        val snapshot = json.decodeFromJsonElement(GraphSnapshot.serializer(), fixture["snapshot"]!!)
        val adj = GraphTraversal.buildAdjacency(snapshot)

        val cases = fixture["queries"]!!.jsonObject["context"]!!.jsonArray
        for (case in cases) {
            val obj = case.jsonObject
            val name = obj["name"]!!.jsonPrimitive.content
            val req = obj["request"]!!.jsonObject
            val expected = obj["result"]!!.jsonObject

            val r = GraphTraversal.context(
                adj,
                req["nodeId"]!!.jsonPrimitive.content,
                GraphTraversal.ContextOptions(req["maxNeighbors"]!!.jsonPrimitive.int),
            )
            assertNotNull(r, "context[$name] returned null")
            r!!
            assertEquals(expected["nodeId"]!!.jsonPrimitive.content, r.node.id, "context[$name] node id")

            val expectedIncoming = expected["incoming"]!!.jsonArray.size
            val expectedOutgoing = expected["outgoing"]!!.jsonArray.size
            assertEquals(expectedIncoming, r.incoming.size, "context[$name] incoming count")
            assertEquals(expectedOutgoing, r.outgoing.size, "context[$name] outgoing count")
            assertEquals(
                expected["truncated"]!!.jsonPrimitive.boolean,
                r.truncated,
                "context[$name] truncated",
            )
        }
    }

    private fun loadFixture(): JsonObject {
        val stream = javaClass.classLoader.getResourceAsStream("graph/traversal-fixture.json")
            ?: error("traversal-fixture.json not on classpath — re-run graph/core/scripts/dump-fixture.ts --write")
        val text = stream.bufferedReader().readText()
        return json.parseToJsonElement(text).jsonObject
    }

    private fun triple(a: String, b: String, c: String) = Triple(a, b, c)
}

@Serializable
private data class FixtureWrapper(val schema_version: Int)
